spring:
  application:
    name: tourism
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres.rajhtsimmhavwpftclqv}
    password: ${DB_PASSWORD:Huyen25092003@}
    url: ${DB_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false