name: Backend Scan Build
run-name: Start build at branch ${{ github.ref_name }}

on:
  push:
    branches: 
      - '**' # Run build on all branch

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
  test:
   runs-on: self-hosted
   needs: build
   steps:
   - name: Run UT test
     run: mvn test
  
