name: DEPLOYMENT
run-name: Deploy to branch ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "release/v1.0"

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    env:
      NEW_FILE_NAME: app.jar
      RUN_PATH: /home/viettravel-be
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build package with Maven
        run: mvn clean package -DskipTests

      - name: Rename JAR File
        run: mv target/*.jar target/${{ env.NEW_FILE_NAME }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Viettravel
          path: target/${{ env.NEW_FILE_NAME }}

  deploy:
    runs-on: self-hosted
    env:
      RUN_PATH: /home/viettravel-be
      JAR_NAME: app.jar
      APP_PATH: /home/viettravel-be/app.jar
      APP_SERVICE: gha-be
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Viettravel
          path: /tmp
  
      - name: Move JAR to RUN_PATH
        run: |
          sudo mkdir -p ${{ env.RUN_PATH }}
          sudo mv /tmp/${{ env.JAR_NAME }} ${{ env.APP_PATH }}
          sudo chmod +x ${{ env.APP_PATH }}
  
      - name: Restart Application
        run: |
          echo "START RELOAD APPLICATION!!!"
          sudo systemctl restart ${{ env.APP_SERVICE }}
